rails/config/routes.rb
SevenBoom::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'booms#home'

  devise_for  :users,
              :path_names =>  {
                :sign_in => "login",
                :sign_out => "logout",
                :sign_up => "register"
              },
              :controllers => {
                :omniauth_callbacks => "omniauth_callbacks",
                :registrations      => "users/registrations"
              }

  # boom operations
  match "/boom/nuevo"                 => "booms#edit",        :as => "new_boom"
  match "/:id/edit"                   => "booms#edit",        :as => "edit_boom"
  match "/boom/fav"                   => "booms#fav",         :as => "boom_fav"
  match "/boom/unfav"                 => "booms#unfav",       :as => "boom_unfav"
  match "/boom/search"                => "booms#search",      :as => "boom_search", :via => "post"

  # user stuff
  match "/usuario/:id"                => "users#profile"
  match "/usuario/:id/:username"      => "users#profile",     :as => "user_profile"

  # boom views
  match "/:category_slug/:boom_slug"  => "booms#show",        :as => "boom"
  match "/:category_slug"             => "booms#bycategory",  :as => "bycategory"

end

rails/app/views/layouts/_daily.html.slim
div.daily.block-sidebar
  h2.block-title 7 Diarios
  .bordered
    h3.daily-title 7 Consejos para el apocalipso
    ul.row-list
      li.odd
        p.position 1
        h4.single Qué dios te agarre confesado
        p Vestibulum vulputate sagittis nulla at cursus. In quis mauris non.
      li.even
        p.position 2
        h4.single Qué dios te agarre confesado
        p Vestibulum vulputate sagittis nulla at cursus. In quis mauris non.
      li.odd
        p.position 3
        h4.single Qué dios te agarre confesado
        p Vestibulum vulputate sagittis nulla at cursus. In quis mauris non.
      li.even
        p.position 4
        h4.single Qué dios te agarre confesado
        p Vestibulum vulputate sagittis nulla at cursus. In quis mauris non.
      li.odd
        p.position 5
        h4.single Qué dios te agarre confesado
        p Vestibulum vulputate sagittis nulla at cursus. In quis mauris non.
      li.even
        p.position 6
        h4.single Qué dios te agarre confesado
        p Vestibulum vulputate sagittis nulla at cursus. In quis mauris non.
      li.odd
        p.position 7
        h4.single Qué dios te agarre confesado
        p Vestibulum vulputate sagittis nulla at cursus. In quis mauris non.
    = link_to "Ver más", "#", :class => "more"

rails/app/views/layouts/_footer.html.slim
footer.main
  div.wrapper.cf
    div.about
      p.head
        = "Sobre "
        span.sp-button 7boom
      p 7boom es una herramienta de socialización 
        a partir de tu opinión. El espacio donde 
        tú ordenas al mundo como tú quieras.
      p El límite es el siete.

      ul.social.cf
        li.fb = link_to "facebook", "#", :class => "sp-button"
        li.tw = link_to "twitter", "#", :class => "sp-button"

      p
        = "7boom es un sitio de "
        = link_to "Brutal Content", "#", :class => "sp-button brutal"

    div.brands
      p.head TU MARCA
      p ¿Te interesa anunciarte en 7boom?
      p Contáctanos:
      p = link_to "contacto@7boom.mx", "mailto:contacto@7boom.mx"
      p.benefits ¡Checa los beneficios!
      = link_to "CLIC AQUÍ", "#", :class => "gr-button"

    div.newsletter
      p.head Recibe nuestro newsletter
      form
        input type="textbox" placeholder="Nombre"
        input type="textbox" placeholder="Correo electrónico"
        = submit_tag "Enviar", :class => "gr-button"
      p Copyright © 2012 · All Rights Reserved

rails/app/views/layouts/_header.html.slim
header.main
  div.wrapper.cf
    nav.cf
      = link_to image_tag("logo.png", {:alt => "7boom", :width => "163", :height => "92"}), root_url, :class => "to-home"
      ul.cf.left-side
        li
          = link_to "Música", "#"
        li
          = link_to "Sexo", "#"
        li
          = link_to "Cine", "#"
        li
          = link_to "Tecnología", "#"
        li
          = link_to "Deportes", "#"
        li
          = link_to "Gourmet", "#"
        li
          = link_to "TV", "#"
        li
          = link_to "Humor", "#"
        li
          = link_to "+", "#"
        li
          form.search-box
            input type="textbox"
            = submit_tag "Buscar", :class => 'sp-button'
    p.tab-button
      = link_to new_boom_path do
        = "Crea tu "
        span.sp-button boom

rails/app/views/layouts/_main_slider.html.slim
div#main-slider.slider
  div.nav
    = link_to "Anterior", "#", :class => "prev sp-button"
    = link_to "Siguiente", "#", :class => "next sp-button"
  ul.slides.cf
    - @slider.each do |boom|
      - url = boom_path(boom.category.slug, boom.slug)
      li.left-side
        = link_to image_tag(boom.image.path_url(:large), :alt => boom.title), url, { :class => "left-side"}
        div.info.right-side
          h2
            = link_to boom.title, url
          p.author
            = "Por "
            = link_to boom.user.username, user_profile_path(boom.user.id, boom.user.username)
          p.excerpt
            = boom.summary

  ul.thumbs.cf
    - @slider.each do |boom|
      - url = boom_path(boom.category.slug, boom.slug)
      li.left-side
        = link_to image_tag(boom.image.path_url(:thumb), :alt => boom.title), url

rails/app/views/layouts/_sidebar.html.slim
div.sidebar.right-side
  = render 'layouts/tops'
  = render 'layouts/daily'

rails/app/views/layouts/_tops.html.slim
#tops.block-sidebar
  ul.tabs
    li.active
        = link_to "Más vistos", "#mas-vistos"
    li
        = link_to "Más comentados", "#mas-comentados"

  .tabbed-content
    ul.row-list.active#mas-vistos
      li.cf.odd
        = link_to image_tag("http://placehold.it/60x60"), "#", :class => "left-side"
        h3 = link_to "Las 7 narices más bonitas del cine de acción", "#"
        = link_to "Juani Juanon", "#", :class => "author"
      li.cf.even
        = link_to image_tag("http://placehold.it/60x60"), "#", :class => "left-side"
        h3 = link_to "Las 7 narices más bonitas del cine de acción", "#"
        = link_to "Juani Juanon", "#", :class => "author"
      li.cf.odd
        = link_to image_tag("http://placehold.it/60x60"), "#", :class => "left-side"
        h3 = link_to "Las 7 narices más bonitas del cine de acción", "#"
        = link_to "Juani Juanon", "#", :class => "author"
      li.cf.even
        = link_to image_tag("http://placehold.it/60x60"), "#", :class => "left-side"
        h3 = link_to "Las 7 narices más bonitas del cine de acción", "#"
        = link_to "Juani Juanon", "#", :class => "author"
      li.cf.odd
        = link_to image_tag("http://placehold.it/60x60"), "#", :class => "left-side"
        h3 = link_to "Las 7 narices más bonitas del cine de acción", "#"
        = link_to "Juani Juanon", "#", :class => "author"

    ul.row-list#mas-comentados
      li.cf.odd
        = link_to image_tag("http://placehold.it/60x60"), "#", :class => "left-side"
        h3 = link_to "Las 99 narices más bonitas del cine de acción", "#"
        = link_to "Juani Juanon", "#", :class => "author"
      li.cf.even
        = link_to image_tag("http://placehold.it/60x60"), "#", :class => "left-side"
        h3 = link_to "Las 7 narices más bonitas del cine de acción", "#"
        = link_to "Juani Juanon", "#", :class => "author"
      li.cf.odd
        = link_to image_tag("http://placehold.it/60x60"), "#", :class => "left-side"
        h3 = link_to "Las 7 narices más bonitas del cine de acción", "#"
        = link_to "Juani Juanon", "#", :class => "author"
      li.cf.even
        = link_to image_tag("http://placehold.it/60x60"), "#", :class => "left-side"
        h3 = link_to "Las 7 narices más bonitas del cine de acción", "#"
        = link_to "Juani Juanon", "#", :class => "author"
      li.cf.odd
        = link_to image_tag("http://placehold.it/60x60"), "#", :class => "left-side"
        h3 = link_to "Las 7 narices más bonitas del cine de acción", "#"
        = link_to "Juani Juanon", "#", :class => "author"

rails/app/views/layouts/_user_panel.html.slim
div#user-panel.user-panel
  - if user_signed_in?
    div.bar-toggle.cf
      div.left-side.social
        ul
          li.tw-follow
            h2 Síguenos:
            = link_to "@7_boom", "#"
          li.fb-like-button
      div.right-side.quick-access
        div.left-side.cf
          ul.quick-options.left-side
            li.dropdown
              / Estos son los links de manejo de sesión
              / hay que usar user_signed_in? para evaluar
              / si el usuario ya está registrado.
              = "Bienvenido "
              strong = link_to current_user.username, user_profile_path(current_user.id, current_user.username)
              ul.dropdown-content
                li
                  p = link_to 'Editar mi perfil', edit_user_registration_path
                li
                  p = link_to 'Cerrar sesión', destroy_user_session_path
            li#panel-trigger
              = "Tu panel"

    .panel#panel
      #panel-wrap.collapse
        .profile.left-side
          .card.col-2.cf
            .column#profile-info
              - if current_user.avatar
                = link_to image_tag(current_user.avatar_url, :alt => current_user.username), "#", :class => "pull-left user-thumb"
              .info
                h2.profile-username
                  = link_to current_user.username, user_profile_path(current_user.id, current_user.username)
                ul.options
                  li
                    = link_to "Editar perfil", edit_user_registration_path, :class => "arrow"
                  li
                    = link_to "Cambiar foto", "#", :class => "arrow"
                .bio
                  p.subtitle BIO:
                  = current_user.bio
            .column#connect
              p
                = link_to "FacebookAccount", "#", :class => "fb-connect"
                = link_to "TwitterAccount", "#", :class => "tw-connect"

          .columns.col-2#user-social-interaction
            .column.following
              h3.subtitle Boomers que sigues
              ul.cf
                li.left-side
                  = link_to image_tag("http://lorempixel.com/50/50/people/1"), "#"
                li.left-side
                  = link_to image_tag("http://lorempixel.com/50/50/people"), "#"
                li.left-side
                  = link_to image_tag("http://lorempixel.com/50/50/people/3"), "#"
                li.left-side
                  = link_to image_tag("http://lorempixel.com/50/50/people/4"), "#"
                li.left-side
                  = link_to image_tag("http://lorempixel.com/50/50/people/5"), "#"
                li.left-side
                  = link_to image_tag("http://lorempixel.com/50/50/people/6"), "#"
                li.left-side
                  = link_to image_tag("http://lorempixel.com/50/50/people/7"), "#"
              p = link_to "Ver todos", "#", :class => "arrow"
            .column.badges
              h3.subtitle Badges

        .right-side.tab-block.tabs-2#panel-activity
          ul.tabs
            li.active
              a[href="#panel-user-activity"] Actividad
            li
              a[href="#panel-user-favs"] Favoritos
          .tabbed-content
            .tab-content.active#panel-user-activity
              ul.activity-list
                - @placeholder = [1, 2, 3, 4, 5, 6, 7]
                - @placeholder.each do |el|
                  li 
                    = link_to image_tag('http://placehold.it/50x50'), '#', :class => 'activity-thumb' 
                    p.activity-description
                      = "Activity"
                      = el

            .tab-content#panel-user-favs
              ul.activity-list
                - @placeholder.each do |el|
                  li 
                    = link_to image_tag('http://placehold.it/50x50'), '#', :class => 'activity-thumb' 
                    p.activity-description
                      = "Fav"
                      = el
                

  - else
    .bar-toggle.not-signed.cf
      .left-side.social
        ul
          li.tw-follow
            h2 Síguenos:
            = link_to "@7_boom", "#"
          li.fb-like-button


      .right-side.quick-access
        ul.quick-options
          li
             = link_to "Ya tengo cuenta", new_user_session_path
          li
             = link_to "Regístrate", new_user_registration_path
          li.tw-login
             = link_to "Entra con twitter", user_omniauth_authorize_path(:twitter)
          li.fb-login
             = link_to "Entra con facebook", user_omniauth_authorize_path(:facebook)

rails/app/views/layouts/application.html.slim
doctype 5
html
  head
    title = content_for(:title)
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags
    link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic' rel='stylesheet' type='text/css'
  body
    .viewport
      - if !notice.nil?
        .notice= notice
      - if !alert.nil?
        .alert= alert

      = render 'layouts/header'

      div.wrapper.cf
        = render 'layouts/user_panel'
        - if @slider
          = render 'layouts/main_slider'

        div.content.left-side
          = yield

        = render 'layouts/sidebar'

      = render 'layouts/footer'
      = javascript_include_tag "application"
      = yield(:javascripts)

      #fb-root

      javascript:
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));