rails/config/routes.rb
SevenBoom::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'booms#home'

  devise_for  :users,
              :path_names =>  {
                :sign_in => "login",
                :sign_out => "logout",
                :sign_up => "register"
              },
              :controllers => {
                :omniauth_callbacks => "omniauth_callbacks",
                :registrations      => "users/registrations"
              }

  # boom operations
  match "/boom/nuevo"                 => "booms#edit",        :as => "new_boom"
  match "/:id/edit"                   => "booms#edit",        :as => "edit_boom"
  match "/boom/fav"                   => "booms#fav",         :as => "boom_fav"
  match "/boom/unfav"                 => "booms#unfav",       :as => "boom_unfav"
  match "/boom/search"                => "booms#search",      :as => "boom_search", :via => "post"

  # user stuff
  match "/usuario/:id"                => "users#profile"
  match "/usuario/:id/:username"      => "users#profile",     :as => "user_profile"

  # boom views
  match "/:category_slug/:boom_slug"  => "booms#show",        :as => "boom"
  match "/:category_slug"             => "booms#bycategory",  :as => "bycategory"

end

rails/app/models/boom.rb
# encoding: utf-8
class Boom < ActiveRecord::Base

  attr_accessible :nsfw, :parent_id, :slug, :summary, :title, :user_id, :category_id,
                  :element_attributes, :image_attributes, :tag_list, :featured

  just_define_datetime_picker :featured, :add_to_attr_accessible => true

  belongs_to  :user
  belongs_to  :category
  belongs_to  :image
  has_many    :element,
              :order => 'position ASC, id ASC',
              :dependent => :delete_all

  accepts_nested_attributes_for :image, :category
  accepts_nested_attributes_for :element,
                                :reject_if => :all_blank,
                                :allow_destroy => true

  acts_as_taggable
  acts_as_nested_set

  acts_as_url :title,
    :url_attribute => :slug,
    :sync_url => true

  validates :title,   :presence   => {
    :message => 'Te falta el título del boom'
  }
  validates :slug,    :uniqueness => true
  validates :summary, :presence   => {
    :message => 'Falta la descripción del boom'
  }
  validates :user_id, :presence   => true

  validates :element,
    :length => {
      :minimum => 7,
      :maximum => 7,
      :message => "Oh, you! Debes escribir 7 puntos, no más, no menos"
    }

  #pretty urls
  def to_param
    "#{category.slug}/#{slug}"
  end

  def recreate_image
    if image?
      image.recreate_versions!
    end
  end

end

rails/app/controllers/booms_controller.rb
class BoomsController < ApplicationController

  def home
    # slider
    @slider = nil

    # recomendados
    @featured = Boom.order("featured DESC").limit(7)

    @weekly = ListGroup.find_by_block_and_name( "home_page", "semanal" )

  end

  def show
    @boom = Boom.find_by_slug!(params[:boom_slug])
    if current_user
      @fav = Favorite.find_by_user_id_and_boom_id(
        current_user.id,
        @boom.id
      ) || Favorite.new
    end
  end

  def bycategory
    @booms = Boom.joins(:category).where('categories.slug' => params[:category_slug])
  end

  def edit
    redirect_to user_session_path if !current_user

    @boom = Boom.new

    if params[:id]

      # edit GET
      @boom = Boom.find_by_id!(params[:id])

      # check authorship
      if !current_user.id.equal?(@boom.user_id)
        flash[:notice] = "Oh, you! ese no es un boom tuyo"
        redirect_to root_path
      end

    end

    if params[:boom]
      #edit POST
      @boom.user_id = current_user.id

      # el slice previene inyección de campos adicionales que pudieran
      # ser importantes, como :featured que debe ser decidido por un
      # administrador, no por el autor

      sanitized_params = params[:boom].slice(:title, :summary, :category_id, :image_attributes, :tag_list, :element_attributes)

      #params[:boom][:element_attributes].each do |i, element|
      #  params[:boom][:element_attributes][i].delete :community_position if params[:element][i][:community_position]
      #end

      #sanitized_params[:element_attributes] = params[:element_attributes]

      if @boom.update_attributes sanitized_params
        redirect_to boom_path(@boom.category.slug, @boom.slug)
      end
      # otherwise let the form render,
      # the errors will be displayed with
      # f.object.errors
    elsif !params[:id]
      #new GET
      7.times { @boom.element.build }
    end

    @i = 0

  end

  # adds a favorite
  def fav
    response = {
      :message => "Tienes que registrarte para tener favoritos"
    }
    if current_user and params[:favorite][:boom_id]
      fav = Favorite.find_or_initialize_by_boom_id_and_user_id(
        params[:favorite][:boom_id],
        current_user.id
      )
      if fav.new_record?
        if fav.save
          response[:message] = "Hecho"
        else
          response[:error] = fav.errors.full_messages.last
        end
      end
    end
    if request.xhr?
      render :json => response
    else
      redirect_to :back
    end
  end

  # removes a favorite
  def unfav
    response = {
      :message => "Tienes que registrarte modificar favoritos"
    }
    if current_user and params[:favorite][:boom_id]
      fav = Favorite.find_by_boom_id_and_user_id!(
        params[:favorite][:boom_id],
        current_user.id
      )
      if fav.destroy
        response[:message] = "Hecho"
      else
        response[:error] = fav.errors.full_messages.last
      end
    end
    if request.xhr?
      render :json => response
    else
      redirect_to :back
    end
  end

  def search
    if request.xhr?
      response = {
        :message => message,
      }
      render :json => response.to_json
    else
      flash[:notice] = message
      redirect_to :back
    end
  end

end

rails/app/helpers/booms_helper.rb
module BoomsHelper
end

rails/app/views/booms/_favorite_form.html.slim
- action = "/boom/%s" % [!@fav.id ? 'fav' : 'unfav']
- text   = !@fav.id ? 'Agregar a mis favoritos' : 'Quitar de mis favoritos'
= semantic_form_for @fav, :url => action  do |b|
  = b.input :boom_id,
            :as => :hidden,
            :value => @boom.id
  = b.action :submit, :label => text

rails/app/views/booms/_recommended.html.slim
div.cf.recommended.list.cols-2
  p.block-title Recomendados
  ul
    li.boom.cat-1.odd
      div.image-block
        = link_to image_tag("http://placehold.it/327x165"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3.px18 = link_to "Fusce in tortor eu quam pellentesque condimentum at et, zomfg, más texto y más texto, omg.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-2.even
      div.image-block
        = link_to image_tag("http://placehold.it/327x165"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3.px18 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-3.odd
      div.image-block
        = link_to image_tag("http://placehold.it/327x165"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3.px18 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-4.even
      div.image-block
        = link_to image_tag("http://placehold.it/327x165"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3.px18 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"

    /Three Columns
    li.boom.cat-5.left-side.small-thumb
      div.image-block
        = link_to image_tag("http://placehold.it/217x109"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-6.left-side.small-thumb
      div.image-block
        = link_to image_tag("http://placehold.it/217x109"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-7.left-side.small-thumb
      div.image-block
        = link_to image_tag("http://placehold.it/217x109"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"

rails/app/views/booms/_user-booms.html.slim
div.user-booms.list.cf.cols-3
  p.block-title Booms de usuarios
  ul
    li.boom.cat-1.left-side.first
      div.image-block
        = link_to image_tag("http://placehold.it/217x109"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-2.left-side
      div.image-block
        = link_to image_tag("http://placehold.it/217x109"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-3.left-side
      div.image-block
        = link_to image_tag("http://placehold.it/217x109"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-4.left-side.first
      div.image-block
        = link_to image_tag("http://placehold.it/217x109"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-5.left-side
      div.image-block
        = link_to image_tag("http://placehold.it/217x109"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-6.left-side
      div.image-block
        = link_to image_tag("http://placehold.it/217x109"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
    li.boom.cat-7.left-side.first
      div.image-block
        = link_to image_tag("http://placehold.it/217x109"), "#", {:class => "list-thumb"}
        p.category
          = link_to "Música", "#"
      div
        h3 = link_to "Fusce in tortor eu quam pellentesque condimentum at et.", "#"
        p.info
          = link_to "Por Usuario Juani, ", "#", :class => "author"
          = "20 de abril 2013"
  = link_to image_tag("http://www.placehold.it/388x177", :alt => "Placeholder"), "#", :class => "right-side"

rails/app/views/booms/_weekly.html.slim
- if @weekly
  div.weekly.list
    p.block-title Booms de la semana
    ul
      - @weekly.list_element.each do |element|
        li class="cf boom cat-#{element.boom.category.position}"
          p.position.left-side
            span = element.position
          div.image-block.left-side
            = link_to image_tag(element.image.path_url(:wide_thumb), :alt => element.title), element.url, {:class => "list-thumb"}
            p.category
              = link_to element.boom.category.name, element.boom.category.slug
          div.title-block
            div.multi-line
              h3.px18.title = link_to element.title, element.url
              p.info
                = link_to "Por #{element.boom.user.username}, ", "usuario/#{element.boom.user.id}", :class => "author"
                = I18n.l element.boom.created_at, :format => :lists
- else
  h2 No hay booms semanales :(

rails/app/views/booms/bycategory.html.slim
- if !@booms.empty?
  pre
    = debug(@booms)
- else
  h1
    | No encontramos booms para #{params[:category_slug]}

rails/app/views/booms/edit.html.slim
article.boom
  - title "Crea tu boom"
  
  - target = @boom.id ? edit_boom_path(@boom.id) : new_boom_path
  
  
  = semantic_form_for @boom, :url => target, :multipart => true do |f|
  
    = f.semantic_errors *f.object.errors.keys
  
    = f.inputs "Crea tu Boom" do
      header.cf
        div.image-block 
          = f.fields_for :image do |i|
            = i.input :path,
              :label => 'Imagen',
              :hint => i.object[:path] ? f.template.image_tag("/uploads/image/path/%s/thumb_%s" % [i.object[:id], i.object[:path]]) : ""
          - if f.object.image.nil?
            = f.fields_for :image_attributes do |im|
              = im.input :path,
                :label => 'Imagen',
                :as => 'file',
                :hint => "Agrega una imagen para per la previsualización"
          p.category
            = f.input :category_id,
              :as => :select,
              :collection => Category.all,
              :include_blank => false,
              :label => 'Categoría',
              :input_html => {:class => "formtasty"},
              :wrap_html => {}
            
        h1   
          = f.input :title, 
            :label => 'Título', 
            :input_html => {:class => "masked-input-text formtasty", :placeholder => 'Escribe aquí tu título'}
        .summary
          = f.input :summary, 
            :label => 'Descripción', 
            :input_html => {:class => "tinymce"}
        .tags
          = f.input :tag_list,
              :label => 'Tags',
              :hint => 'Separados por comas'
    
      = f.fields_for :element do |el|
        - @i += 1
        section.boom-element
          div.cf.element-top
            p.position.left-side
             span = @i
            div.title-block
              div.multi-line
                = el.input :position,
                  :as => 'hidden',
                  :wrapper_html => {:style => "display:none"},
                  :value => @i
                = el.input :title, 
                  :label => false, 
                  :placeholder => "Título del boom %s" % @i,
                  :input_html => {:class => 'masked-input-text'}
                  
          div.content-blocks
            = el.input :content, 
              :label => false
      
            = el.fields_for :image do |im|
              = im.input :path, :label => 'Imagen',
                :hint => im.object[:path] ? el.template.image_tag("/uploads/image/path/%s/thumb_%s" % [im.object[:id],
                im.object[:path]]) : ""
      
            - if el.object.image.nil?
              = el.fields_for :image_attributes do |im|
                = im.input :path,
                  :label => 'Imagen',
                  :as => 'file',
                  :hint => "Agrega una imagen para per la previsualización"
  
    = f.action :submit, :label => '¡Publicar!'

rails/app/views/booms/home.html.slim
- title "7boom"

= render 'booms/recommended'

= render 'booms/user-booms'

= render 'booms/weekly'

rails/app/views/booms/show.html.slim
- title "%s | 7boom" % @boom.title
- author = @boom.user
article class="boom cat-#{@boom.category.position}"
  header.cf
    div.image-block
      = image_tag @boom.image.path_url(:large), :alt => @boom.title
      p.category
        = link_to @boom.category.name, @boom.category.slug
    h1 = @boom.title
    p.summary
      = @boom.summary
    div.cf.social-bar
      div.text-block.left-side
        - if author.avatar
          = link_to image_tag(author.avatar_url(:small_thumb), :alt => "Usuario: #{author.username}"), "usuario/#{@boom.user_id}", :class => "user-thumb"
        div.multi-line
          p.info
            = "Por "
            = link_to "#{author.username} ", "usuario/#{author.id}", :class => "author"
      div.social
        p COMPARTE:
        a.twitter-share-button href="https://twitter.com/share" data-lang="es"
          = "Tweet"
        div.fb-like data-href="http://local.7boom.mx" data-send="false" data-layout="button_count" data-width="120" data-show-faces="false"

  - @boom.element.order("position DESC").each do |el|
    section.boom-element
      div.cf.element-top
        p class="position left-side pos-#{el.position}"
          span = el.position
        div.title-block
          div.multi-line
            h2 = el.title
      div.content-blocks
        - if el.image
          div.block
            = image_tag el.image.path_url(:boom), :alt => el.title
        - if el.content
          div.block
            p = el.content

  footer
    p tags
    div.social
      p COMPARTE:
      a.twitter-share-button href="https://twitter.com/share" data-lang="es"
        = "Tweet"
      div.fb-like data-href="http://local.7boom.mx" data-send="false" data-layout="button_count" data-width="120" data-show-faces="false"
    div.text-block.left-side
      - if author.avatar
        = link_to image_tag(author.avatar_url(:medium_thumb), :alt => "Usuario: #{author.username}"), "usuario/#{@boom.user_id}", :class => "user-thumb"
      div.multi-line
        p.info
          = "Publicado por "
          = link_to "#{author.username} ", "usuario/#{author.id}", :class => "author"
        p.bio = author.bio


- if current_user and current_user.id == @boom.user_id
  = link_to("Editar", edit_boom_path(@boom.id))

javascript:
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
div#fb-root
  javascript:
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=140063816168588";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>